/* m68k_op_ABCD_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the ABCD op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_SRC_FN(n) _OP_PASTE(OP_HAM_SRC, n)
#define HAM_DST_FN(n) _OP_PASTE(OP_HAM_DST, n)

static INLINE void OP_NAME(M68K* z, struct OP_HAM_SRC* src, struct OP_HAM_DST* dst)
{

 bool V = false;
 uint8_t const src_data = HAM_SRC_FN(_read)(src);
 uint8_t const dst_data = HAM_DST_FN(_read)(dst);
 uint32_t tmp;

 tmp = dst_data + src_data + GetX(z);

 if(((dst_data ^ src_data ^ tmp) & 0x10) || (tmp & 0xF) >= 0x0A)
 {
  uint8_t prev_tmp = tmp;
  tmp += 0x06;
  V |= ((~prev_tmp & 0x80) & (tmp & 0x80));
 }

 if(tmp >= 0xA0)
 {
  uint8_t prev_tmp = tmp;
  tmp += 0x60;
  V |= ((~prev_tmp & 0x80) & (tmp & 0x80));
 }

 CalcZN_u8_clear(z, tmp);
 SetCX(z, (bool)(tmp >> 8));
 z->Flag_V = V;

 if(OP_DAM == DATA_REG_DIR)
  z->timestamp += 2;
 else
  z->timestamp += 4;

 HAM_DST_FN(_write)(dst, tmp, 2);
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_SRC_FN
#undef HAM_DST_FN
#undef OP_NAME
#undef OP_HAM_SRC
#undef OP_HAM_DST
#undef OP_T
#undef OP_SAM
#undef OP_DAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
