/* m68k_op_RotateBase_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the RotateBase op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_TARG_FN(n) _OP_PASTE(OP_HAM_TARG, n)

static MDFN_FORCE_INLINE void OP_NAME(M68K* z, bool X_Form, bool ShiftLeft, struct OP_HAM_TARG* targ, unsigned count)
{
 OP_T result = HAM_TARG_FN(_read)(targ);
 count &= 0x3F;

 if(OP_TAM == DATA_REG_DIR)
  z->timestamp += (OP_TSIZE == 4) ? 4 : 2;

 if(count == 0)
 {
  if(X_Form)
   z->Flag_C = GetX(z);
  else
   z->Flag_C = false;
 }
 else
 {
  bool shifted_out = GetX(z);

  do
  {
   const bool shift_in = shifted_out;

   if(OP_TAM == DATA_REG_DIR)
    z->timestamp += 2;

   if(ShiftLeft)
   {
    shifted_out = (result >> (OP_TSIZE * 8 - 1)) & 1;
    result <<= 1;
    result |= (X_Form ? shift_in : shifted_out);
   }
   else
   {
    shifted_out = (result & 1);
    result >>= 1;
    result |= (OP_T)(X_Form ? shift_in : shifted_out) << (OP_TSIZE * 8 - 1);
   }
  } while(--count != 0);

  z->Flag_C  = shifted_out;
  if(X_Form)
   z->Flag_X = shifted_out;
 }

 CALC_ZN(z, OP_T, result);
 z->Flag_V = (false);

 HAM_TARG_FN(_write)(targ, result, 2);
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_TARG_FN
#undef OP_NAME
#undef OP_HAM_TARG
#undef OP_T
#undef OP_TAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
