/* m68k_op_MULS_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the MULS op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_SRC_FN(n) _OP_PASTE(OP_HAM_SRC, n)

static INLINE void OP_NAME(M68K* z, struct OP_HAM_SRC* src, const unsigned dr)
{
 // Doesn't affect X flag

 OP_T const src_data = HAM_SRC_FN(_read)(src);
 uint32_t const result = (int16_t)z->D[dr] * (int16_t)src_data;

 z->timestamp += 34;

 for(uint32_t tmp = src_data << 1, i = 0; i < 16; tmp >>= 1, i++)
  z->timestamp += (tmp ^ (tmp << 1)) & 2;

 CalcZN_u32(z, result);
 z->Flag_C = false;
 z->Flag_V = false;

 z->D[dr] = result;
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_SRC_FN
#undef OP_NAME
#undef OP_HAM_SRC
#undef OP_T
#undef OP_SAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
