/* m68k_op_TAS_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the TAS op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_DST_FN(n) _OP_PASTE(OP_HAM_DST, n)

static INLINE void OP_NAME(M68K* z, struct OP_HAM_DST* dst)
{

 (void)z; /* TAS_Callback is a file-scope free function (not a method);
           * dst->rmw passes it M68K* via dst->zptr internally, so the
           * outer z isn't read here. */
 HAM_DST_FN(_rmw)(dst, TAS_Callback);
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_DST_FN
#undef OP_NAME
#undef OP_HAM_DST
#undef OP_T
#undef OP_DAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
