/* m68k_op_MOVEM_to_REGS_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the MOVEM_to_REGS op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_SRC_FN(n) _OP_PASTE(OP_HAM_SRC, n)

static INLINE void OP_NAME(M68K* z, bool pseudo_postinc, struct OP_HAM_SRC* src, const uint16_t reglist)
{

 uint32_t ea = HAM_SRC_FN(_getea)(src);

 for(unsigned i = 0; i < 16; i++)
 {
  if(reglist & (1U << i))
  {
   /* Phase-8s-pre: Read<OP_T>(ea) inlined.  OP_TSIZE folds at
    * MOVEM_to_REGS template instantiation. */
   OP_T tmp;
   if(OP_TSIZE == 1)      tmp = Read_u8(z, ea);
   else if(OP_TSIZE == 2) tmp = Read_u16(z, ea);
   else                    tmp = Read_u32(z, ea);

   z->DA[i] = (OP_T_SIGNED)(tmp);

   ea += OP_TSIZE;
  }
 }

 Read_u16(z, ea);	// or should be <OP_T> ?

 if(pseudo_postinc)
  z->A[src->reg] = ea;
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_SRC_FN
#undef OP_NAME
#undef OP_HAM_SRC
#undef OP_T
#undef OP_SAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
