/* m68k_op_MOVEM_to_MEM_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the MOVEM_to_MEM op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_DST_FN(n) _OP_PASTE(OP_HAM_DST, n)

static INLINE void OP_NAME(M68K* z, bool pseudo_predec, const uint16_t reglist, struct OP_HAM_DST* dst)
{

 uint32_t ea = HAM_DST_FN(_getea)(dst);

 for(unsigned i = 0; i < 16; i++)
 {
  if(reglist & (1U << i))
  {
   if(pseudo_predec)
    ea -= OP_TSIZE;

   const OP_T val = z->DA[pseudo_predec ? (15 - i) : i];

   if(OP_TSIZE == 4)
   {
    if(pseudo_predec)
     Write_u32_longdec(z, ea, val);
    else
     Write_u32(z, ea, val);
   }
   else if(OP_TSIZE == 2)
    Write_u16(z, ea, val);
   else
    Write_u8(z, ea, val);

   if(!pseudo_predec)
    ea += OP_TSIZE;
  }
 }

 if(pseudo_predec)
  z->A[dst->reg] = ea;
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_DST_FN
#undef OP_NAME
#undef OP_HAM_DST
#undef OP_T
#undef OP_DAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
