/* m68k_op_ROL_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the ROL op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_TARG_FN(n) _OP_PASTE(OP_HAM_TARG, n)

static INLINE void OP_NAME(M68K* z, struct OP_HAM_TARG* targ, unsigned count)
{
 OP_ROTATEBASE(z, false, true, targ, count);
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_TARG_FN
#undef OP_NAME
#undef OP_HAM_TARG
#undef OP_T
#undef OP_TAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
