/* m68k_op_Subtract_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the Subtract op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_SRC_FN(n) _OP_PASTE(OP_HAM_SRC, n)
#define HAM_DST_FN(n) _OP_PASTE(OP_HAM_DST, n)

static MDFN_FORCE_INLINE OP_DT OP_NAME(M68K* z, bool X_form, struct OP_HAM_SRC* src, struct OP_HAM_DST* dst)
{

 uint32_t const src_data = (OP_DT)(OP_T_SIGNED)(HAM_SRC_FN(_read)(src));
 uint32_t const dst_data = HAM_DST_FN(_read)(dst);
 const uint64_t result = (uint64_t)dst_data - src_data - (X_form ? GetX(z) : 0);

 if(OP_DAM == ADDR_REG_DIR)	// SUBA, SUBQ(A) only.
 {
  if(OP_TSIZE != 4 || OP_SAM == DATA_REG_DIR || OP_SAM == ADDR_REG_DIR || OP_SAM == IMMEDIATE)
   z->timestamp += 4;
  else
   z->timestamp += 2;
 }
 else if(OP_DAM == DATA_REG_DIR)	// SUB, SUBQ, SUBX only.
 {
  if(OP_DTSIZE == 4)
  {
   if(OP_SAM == DATA_REG_DIR || OP_SAM == IMMEDIATE)
    z->timestamp += 4;
   else
    z->timestamp += 2;
  }
 }
 else if(OP_DAM == IMMEDIATE)	// NEG, NEGX only and always.
 {
  if(OP_TSIZE == 4)
  {
   z->timestamp += 2;
  }
 }
 else if(OP_SAM != IMMEDIATE && OP_SAM != ADDR_REG_DIR && OP_SAM != DATA_REG_DIR) // SUBX m,m
 {
  z->timestamp += 2;
 }

 if(OP_DAM != ADDR_REG_DIR)
 {
  if(X_form)
   CALC_ZN_CLEAR(z, OP_DT, result);
  else
   CALC_ZN(z, OP_DT, result);
  SetCX(z, (result >> (OP_DTSIZE * 8)) & 1);
  z->Flag_V = (((((dst_data ^ src_data)) & (dst_data ^ result)) >> (OP_DTSIZE * 8 - 1)) & 1);
 }

 return result;
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_SRC_FN
#undef HAM_DST_FN
#undef OP_NAME
#undef OP_HAM_SRC
#undef OP_HAM_DST
#undef OP_T
#undef OP_DT
#undef OP_SAM
#undef OP_DAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
