/* m68k_op_ADDX_body.inc.h
 * Phase-9d-15b: macro-parameterised body of the ADDX op.
 * Auto-generated by tools/gen_op_macros.py. */

#ifndef OP_NAME
#error "OP_NAME must be defined"
#endif

#define _OP_PASTE2(a, b) a ## b
#define _OP_PASTE(a, b) _OP_PASTE2(a, b)
#define HAM_SRC_FN(n) _OP_PASTE(OP_HAM_SRC, n)
#define HAM_DST_FN(n) _OP_PASTE(OP_HAM_DST, n)

static INLINE void OP_NAME(M68K* z, struct OP_HAM_SRC* src, struct OP_HAM_DST* dst)
{
 uint32_t const src_data = HAM_SRC_FN(_read)(src);
 uint32_t const dst_data = HAM_DST_FN(_read)(dst);
 uint64_t const result = (uint64_t)dst_data + src_data + GetX(z);

 if(OP_DAM != DATA_REG_DIR)
 {
  z->timestamp += 2;
 }
 else
 {
  if(OP_TSIZE == 4)
   z->timestamp += 4;
 }

 CALC_ZN_CLEAR(z, OP_T, result);
 SetCX(z, (result >> (OP_TSIZE * 8)) & 1);
 z->Flag_V = ((((~(dst_data ^ src_data)) & (dst_data ^ result)) >> (OP_TSIZE * 8 - 1)) & 1);

 HAM_DST_FN(_write)(dst, result, 2);
}

#undef _OP_PASTE2
#undef _OP_PASTE
#undef HAM_SRC_FN
#undef HAM_DST_FN
#undef OP_NAME
#undef OP_HAM_SRC
#undef OP_HAM_DST
#undef OP_T
#undef OP_SAM
#undef OP_DAM
#undef OP_TSIZE
#undef OP_DTSIZE
#undef OP_T_SIGNED
#undef OP_DT_SIGNED
#undef OP_SUBTRACT
#undef OP_SHIFTBASE
#undef OP_ROTATEBASE
