#!/usr/bin/env python3
# gen_idecodetab2.py
#
# Regenerates mednafen/ss/sh7095_idecodetab2.inc from
# mednafen/ss/sh7095_idecodetab.inc.
#
# The flat decode table is 65536 uint8 entries indexed by the raw 16-bit
# instruction word.  Viewed as 4096 rows of 16 entries (row = instr >> 4,
# column = instr & 0xF), only 48 distinct row patterns exist, so the table
# compresses losslessly into:
#
#   InstrDecodeRowIdx[4096]  (uint8)  -- row pattern index for instr >> 4
#   InstrDecodeRows[N][16]   (uint8)  -- the distinct row patterns
#
# 4096 + N*16 bytes total (4864 bytes at N=48) versus 65536 bytes flat.
# A decode is two dependent byte loads:
#
#   op = InstrDecodeRows[InstrDecodeRowIdx[instr >> 4]][instr & 0xF]
#
# The point is L1 dcache footprint, not latency: one RowIdx cache line
# covers a 1024-encoding span of instruction space (vs 64 for the flat
# table), and the entire Rows array is 12 lines that stay pinned.  The
# extra load's latency is hidden: the decoded op is written into the
# high byte of Pipe_ID and not consumed until the following Step's
# dispatch, a full emulated instruction later.
#
# This script verifies the compressed form against the flat table for
# all 65536 encodings before writing anything.  If the flat table ever
# grows more than 256 distinct rows (uint8 RowIdx overflow), it fails
# loudly rather than emitting a broken table.

import os
import re
import sys

SELF_DIR = os.path.dirname(os.path.abspath(__file__))
SS_DIR = os.path.normpath(os.path.join(SELF_DIR, "..", "mednafen", "ss"))
SRC = os.path.join(SS_DIR, "sh7095_idecodetab.inc")
DST = os.path.join(SS_DIR, "sh7095_idecodetab2.inc")


def load_flat_table(path):
    with open(path, "r") as f:
        text = f.read()
    # Strip /* */ and // comments before tokenizing numbers.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    toks = [t for t in re.split(r"[,\s]+", text) if t]
    vals = [int(t, 0) for t in toks]
    if len(vals) != 65536:
        sys.exit("error: expected 65536 entries in %s, got %d" % (path, len(vals)))
    if any(v < 0 or v > 0xFF for v in vals):
        sys.exit("error: entry out of uint8 range in %s" % path)
    return vals


def main():
    flat = load_flat_table(SRC)

    rows = []            # list of 16-tuples, in first-appearance order
    row_lookup = {}      # 16-tuple -> index in rows
    rowidx = []          # 4096 entries

    for r in range(4096):
        row = tuple(flat[r * 16:(r + 1) * 16])
        idx = row_lookup.get(row)
        if idx is None:
            idx = len(rows)
            row_lookup[row] = idx
            rows.append(row)
        rowidx.append(idx)

    if len(rows) > 256:
        sys.exit("error: %d distinct rows, exceeds uint8 RowIdx" % len(rows))

    # Exhaustive roundtrip check.
    for i in range(65536):
        if rows[rowidx[i >> 4]][i & 0xF] != flat[i]:
            sys.exit("error: roundtrip mismatch at encoding 0x%04X" % i)

    with open(DST, "w") as f:
        f.write("/* Generated by tools/gen_idecodetab2.py from"
                " sh7095_idecodetab.inc -- do not edit.\n")
        f.write(" * Two-level lossless compression of the 64KiB flat"
                " instruction decode table:\n")
        f.write(" *   op = InstrDecodeRows[InstrDecodeRowIdx[instr >> 4]]"
                "[instr & 0xF]\n")
        f.write(" * %d distinct 16-entry rows; %d bytes total.\n" %
                (len(rows), 4096 + len(rows) * 16))
        f.write(" * Verified equivalent for all 65536 encodings at"
                " generation time.\n */\n")
        f.write("static const uint8_t InstrDecodeRowIdx[4096] =\n{\n")
        for base in range(0, 4096, 16):
            line = ", ".join("%3d" % v for v in rowidx[base:base + 16])
            f.write(" %s,\n" % line)
        f.write("};\n\n")
        f.write("static const uint8_t InstrDecodeRows[%d][16] =\n{\n" %
                len(rows))
        for row in rows:
            line = ", ".join("0x%02X" % v for v in row)
            f.write(" { %s },\n" % line)
        f.write("};\n")

    print("wrote %s: %d distinct rows, %d bytes (flat: 65536)" %
          (DST, len(rows), 4096 + len(rows) * 16))


if __name__ == "__main__":
    main()
