#!/usr/bin/env python3
"""
Regenerate sh7095_mem_dispatch.inc + sh7095_mem_dispatch_proto.inc from
the C++ template instantiation list emitted by a baseline build of ss.cpp.

Usage:
  1. Check out a revision that still has the C++ templates (e.g. abb7bf0
     or earlier).  Build ss.cpp; the C_MemReadRT / C_MemWriteRT mangled
     symbols will be present in the .o.
  2. nm <ss.o> | grep -E '_Z(11C_MemReadRT|12C_MemWriteRT)' \
        | awk '{print $3}' | sort -u > /tmp/mangled.txt
  3. tools/gen_mem_dispatch.py /tmp/mangled.txt \
        mednafen/ss/sh7095_mem_dispatch.inc \
        mednafen/ss/sh7095_mem_dispatch_proto.inc

The two output files are the verbatim retirement of the four templates:
    SH7095_MemReadRT, SH7095_MemWriteRT, C_MemReadRT, C_MemWriteRT
into 196 named C functions (124 unique reads + 72 unique writes after
deduping the [clone .cold] variants GCC emits for MDFN_COLD attribute).

Phase-9 step 5 part 2.  Keep in tools/ so the generated .inc can be
regenerated if the template parameter shape ever changes.
"""
import re, subprocess, sys

if len(sys.argv) != 4:
    sys.stderr.write("usage: %s <mangled.txt> <out.inc> <out_proto.inc>\n" % sys.argv[0])
    sys.exit(1)

mangled_path, out_path, proto_path = sys.argv[1:4]

raw = subprocess.check_output(
    ['c++filt'], input=open(mangled_path).read(), text=True
).strip().split('\n')

T_MAP = {'unsigned char':  ('u8',  'uint8_t'),
         'unsigned short': ('u16', 'uint16_t'),
         'unsigned int':   ('u32', 'uint32_t')}

reads, writes = {}, {}

for line in raw:
    line = re.sub(r'\s*\[clone[^]]*\]\s*$', '', line)
    m = re.match(r'(?:unsigned (?:char|short|int))\s+C_MemReadRT<(.*?)>\(unsigned int\)', line)
    if m:
        args = [a.strip() for a in m.group(1).split(',')]
        w = args[0].rstrip('u')
        nsc_demangled = args[1]                      # -1, 0, 1
        cbh_demangled = args[2]                      # true / false
        T_tok, T_c    = T_MAP[args[3]]
        region        = args[4].rstrip('u')
        ce_demangled  = args[5]                      # true / false
        isin          = args[6]                      # -1, 0, 1

        # NeedSlaveCall == -1 was the debug-mode dispatch path; debug mode
        # was removed from this libretro core (no debugger UI) and the
        # `_nm1_` instantiations are no longer needed.
        if nsc_demangled == '-1':
            continue

        nsc_tok = 't' if nsc_demangled == '1' else 'f'
        cbh_tok = 't' if cbh_demangled == 'true' else 'f'
        ce_val  = '1' if ce_demangled == 'true' else '0'
        isin_tok = 'm1' if isin == '-1' else isin
        nsc_val  = nsc_demangled
        cbh_val  = '1' if cbh_demangled == 'true' else '0'

        key = (w, nsc_tok, cbh_tok, T_tok, region, ce_val, isin_tok)
        reads[key] = (w, nsc_tok, cbh_tok, T_tok, T_c, region, ce_val, isin_tok,
                      nsc_val, cbh_val, isin)
        continue

    m = re.match(r'void\s+C_MemWriteRT<(.*?)>\(unsigned int,\s*unsigned (?:char|short|int)\s*\)', line)
    if m:
        args = [a.strip() for a in m.group(1).split(',')]
        w = args[0].rstrip('u')
        nsc_demangled = args[1]
        T_tok, T_c    = T_MAP[args[2]]
        region        = args[3].rstrip('u')
        ce_demangled  = args[4]

        # Same debug-mode skip as for reads.
        if nsc_demangled == '-1':
            continue

        nsc_tok = 't' if nsc_demangled == '1' else 'f'
        ce_val  = '1' if ce_demangled == 'true' else '0'
        nsc_val = nsc_demangled

        key = (w, nsc_tok, T_tok, region, ce_val)
        writes[key] = (w, nsc_tok, T_tok, T_c, region, ce_val, nsc_val)
        continue

    sys.stderr.write("UNPARSED: %s\n" % line)

HEADER = """\
/* GENERATED by tools/gen_mem_dispatch.py from the C++ template
 * instantiation list of the four SH7095 mega-templates.  Do NOT
 * edit by hand; regenerate (see tools/gen_mem_dispatch.py for the
 * exact procedure).
 *
 * Naming scheme: each function suffix encodes the original template
 * arguments, all readable in lower-case identifier characters.
 *   w<W>     -- which CPU                 (0 | 1)
 *   n<NSC>   -- NeedSlaveCall token       (f | t)
 *   c<CBH>   -- CacheBypassHack token     (f | t)        [reads only]
 *   u<BITS>  -- access width              (u8 | u16 | u32)
 *   r<REG>   -- region                    (0..7)
 *   e<CE>   -- CacheEnabled flag (literal 0/1, set by caller MAHL macro)
 *   i<ISI>   -- IsInstr token             (m1 | 0 | 1)          [reads only]
 *
 * The MAHL / MAHL_P macros in RecalcMRWFP_0 / RecalcMRWFP_1_7 compose
 * these names through the C ## operator from the same tokens.  Any
 * mismatch between the name a MAHL invocation composes and the names
 * defined here is a build error (undefined reference at the function-
 * pointer-table assignment line). */
"""

DEFINE_BODY = """\
#define DEFINE_C_MEMREADRT(suffix, T, w_v, nsc_v, cbh_v, region_v, ce_v, isin_v)\\
static NO_INLINE MDFN_FASTCALL T C_MemReadRT_##suffix(uint32_t A)             \\
{                                                                             \\
    enum { which = w_v };                                                     \\
    enum { NeedSlaveCall = nsc_v };                                           \\
    enum { CacheBypassHack = cbh_v };                                         \\
    SH7095* const z = &CPU[w_v];                                              \\
    SH7095_CacheEntry* cent;                                                  \\
    int way_match;                                                            \\
    uint32_t unmasked_A;                                                      \\
    T ret;                                                                    \\
    (void)cent; (void)way_match; (void)unmasked_A;                            \\
    (void)which; (void)NeedSlaveCall; (void)CacheBypassHack;                  \\
    MemRead(isin_v, T, region_v, ce_v, A, ret, A, unmasked_A, cent, way_match); \\
    return ret;                                                               \\
}

#define DEFINE_C_MEMWRITERT(suffix, T, w_v, nsc_v, region_v, ce_v)            \\
static NO_INLINE MDFN_FASTCALL void C_MemWriteRT_##suffix(uint32_t A, T V)    \\
{                                                                             \\
    enum { which = w_v };                                                     \\
    enum { NeedSlaveCall = nsc_v };                                           \\
    enum { CacheBypassHack = 0 };                                             \\
    SH7095* const z = &CPU[w_v];                                              \\
    uint32_t unmasked_A;                                                      \\
    (void)unmasked_A;                                                         \\
    (void)which; (void)NeedSlaveCall; (void)CacheBypassHack;                  \\
    MemWrite(T, region_v, ce_v, A, V, A, unmasked_A, V);                      \\
}

"""

out = [HEADER, '\n', DEFINE_BODY]
out.append('/* %d C_MemReadRT instantiations (124 unique tuples after deduping the\n'
           ' * [clone .cold] variants GCC emits for MDFN_COLD-marked templates). */\n' % len(reads))
for key, v in sorted(reads.items()):
    w, nsc_tok, cbh_tok, T_tok, T_c, region, ce_val, isin_tok, nsc_val, cbh_val, isin = v
    suffix = 'w%s_n%s_c%s_%s_r%s_e%s_i%s' % (w, nsc_tok, cbh_tok, T_tok, region, ce_val, isin_tok)
    out.append('DEFINE_C_MEMREADRT(%s, %s, %s, %s, %s, %s, %s, %s)\n'
               % (suffix, T_c, w, nsc_val, cbh_val, region, ce_val, isin))
out.append('\n/* %d C_MemWriteRT instantiations. */\n' % len(writes))
for key, v in sorted(writes.items()):
    w, nsc_tok, T_tok, T_c, region, ce_val, nsc_val = v
    suffix = 'w%s_n%s_%s_r%s_e%s' % (w, nsc_tok, T_tok, region, ce_val)
    out.append('DEFINE_C_MEMWRITERT(%s, %s, %s, %s, %s, %s)\n'
               % (suffix, T_c, w, nsc_val, region, ce_val))

with open(out_path, 'w') as f:
    f.writelines(out)

# Proto: forward declarations only, so MAHL_/MAHL_P references compile
# at function-pointer-assignment sites without needing the full
# definitions in scope yet.
proto = ['/* GENERATED: forward declarations for the %d C_MemReadRT / %d\n'
         ' * C_MemWriteRT named C functions in sh7095_mem_dispatch.inc.\n'
         ' * Included from sh7095.inc before RecalcMRWFP_0 so the MAHL /\n'
         ' * MAHL_P function-pointer-table assignments compile.  See\n'
         ' * sh7095_mem_dispatch.inc for the full naming scheme. */\n' % (len(reads), len(writes))]
for _, v in sorted(reads.items()):
    w, nsc_tok, cbh_tok, T_tok, T_c, region, ce_val, isin_tok, *_ = v
    suffix = 'w%s_n%s_c%s_%s_r%s_e%s_i%s' % (w, nsc_tok, cbh_tok, T_tok, region, ce_val, isin_tok)
    proto.append('static NO_INLINE MDFN_FASTCALL %s C_MemReadRT_%s(uint32_t A);\n' % (T_c, suffix))
proto.append('\n')
for _, v in sorted(writes.items()):
    w, nsc_tok, T_tok, T_c, region, ce_val, _ = v
    suffix = 'w%s_n%s_%s_r%s_e%s' % (w, nsc_tok, T_tok, region, ce_val)
    proto.append('static NO_INLINE MDFN_FASTCALL void C_MemWriteRT_%s(uint32_t A, %s V);\n' % (suffix, T_c))
with open(proto_path, 'w') as f:
    f.writelines(proto)

print("reads: %d unique, writes: %d unique" % (len(reads), len(writes)))
print("wrote %s" % out_path)
print("wrote %s" % proto_path)
